### ISSUE TITLE
Error of dataset

### ISSUE THREAD

**Issue by Chenyu-Tian** [MattRosenLab/AUTOMAP#2]
It seems like that the dataset at  [MRI Training and Testing Data ](https://www.dropbox.com/s/7ysptucyro6imq8/data.7z?dl=1) is broken.
When I downloaded from this link in different ways, error always occured at 2.7/2.9 GB, which broke the dowloading. Is there another way to accees the dataset?

**Comment by danyalb** [comment]
Hi, 

Can you just confirm you tried downloading with different browsers and with different wifi connection? I was able to download the data with the same link today.

**Comment by Chenyu-Tian** [comment]
Thanks. It works by using Chrome on Ubuntu.
