### ISSUE TITLE
train_fft_x_64.mat does not exist

### ISSUE THREAD

**Issue by eyildiz-ugoe** [MattRosenLab/AUTOMAP#5]
I noticed that the data downloaded does not contain the aforementioned file  (and probably others)  and thus, training is not possible.  I have only the following:

```
11.768.747 test_input.mat
5.911.387 test_x_img.mat
5.886.206 test_x_real.mat
1.541.264.811 train_input.mat
767.614.779 train_x_img.mat
764.841.654 train_x_real.mat
```

Any idea?

**Comment by danyalb** [comment]
Hi,

According to the README, we state: "the data_64 folder contains, 64x64
images, 'train_input.mat' for training AUTOMAP with labels
'train_x_real.mat' and 'train_x_img.mat' for training each neural network
respectively". The train_input.mat is used as training input data. And
test_input.mat as test input.

I will update the config to make it more clear for users.
'train_fft_64.mat' is actually the same file as train_input.mat, just
renamed. All the data files needed to train and test are provided.

Best,
Danyal
