### ISSUE TITLE
requirements versions

### ISSUE THREAD

**Issue by Yacoub-Abulubad** [MattRosenLab/AUTOMAP#8]
I've been facing a lot of issues regarding package incompatibilities and was wondering if there could be a way to retrieve all the requirements by creating a `requirements.txt` file including all used packages and versions which AUTOMAP was built on. Thanks!

**Comment by danyalb** [comment]
Hi,

I added automap_libraries.txt with the requirements using pip freeze. But if you install these below, it should work.

---------------------------------
tensorflow 2.2.0  --> pip install tensorflow==2.2.0
numpy  --> pip install numpy
tqdm  --> pip install tqdm
mat73  --> pip install mat73
scipy  --> pip install scipy
bunch  --> pip install bunch
matplotlib  --> pip install matplotlib
---------------------------------

**Comment by danyalb** [comment]
You do need tensorflow 2.2.0, not a later version.

**Comment by Yacoub-Abulubad** [comment]
Hey, thanks for the response. But I am still facing issues with running the code.
Which python version are you running?

```
model = automap_main_train.main()
  File "/path/to/automap_main_train.py", line 31, in main
    trained_model = trainer.train()
  File "/path/to/ai_mri_reconstruction/trainers/automap_trainer.py", line 111, in train
    loss_training[0, epoch] = self.train_loss
ValueError: setting an array element with a sequence.
```

This is the error im getting and also for some reason the description for the training looks like this
`Epoch: 0 Loss: Tensor("Mean_8:0", shape=(), dtype=float32) Val Loss: Tensor("Mean_9:0", shape=(), dtype=float32)`

Any help would be appreciated

**Comment by danyalb** [comment]
hi, 

I'm using python 3.6.10. 

Can you redownload automap_trainer.py ? I made a change there in line 18 and line 19. Not sure if that was the cause of your error but I updated something there recently that might also solve your error.

**Comment by Yacoub-Abulubad** [comment]
I did redownload automap_trainer.py, but after some more research on the error im getting it seems like it is due to tf not running the computations but rather just creating the 'graphs' as seen in this issue:
https://stackoverflow.com/questions/46548339/tensorflow-tensormul0-shape-dtype-int32
Does this have to do with me using a custom dataset? Because it used to run properly with the .mat files

**Comment by danyalb** [comment]
Can you try having your dataset be np arrays before starting training and see if that makes a difference?

**Comment by Yacoub-Abulubad** [comment]
I have figured out why I was facing that issue, it was because I used to take the `np.abs(input)` in my custom data loader for custom data and did not know that one is supposed to input the data as complex (k-space).

**Comment by Yacoub-Abulubad** [comment]
I think it would be helpful to mention that the input data should be complex in the `README.md` file
