### ISSUE TITLE
Access to model weights

### ISSUE THREAD

**Issue by zwep** [MattRosenLab/AUTOMAP#9]
Hello,

is there a location where I can get the pretrained AUTOMAP model weights? I would like to check the performance of the trained AUTOMAP model for my research

Greetings

**Comment by danyalb** [comment]
Hi, 

AUTOMAP models are trained for each image size, thus we do not provide pre-trained models on github. We provide the training data for 64 by 64 size images and you are welcome to train a model for that size. 

If you would like to reach out to our lab directly regarding your particular case, please email us at DBHUTTO@mgh.harvard.edu.

Best,
